### ISSUE TITLE
Compiling on OSX 10.11.6 with XCode

### ISSUE THREAD

**Issue by anmwinter** [jpsglouzon/supernmotifs#1]
Hello,

 I am trying to run the make command on supernmotifs from source. I am running OSX 10.11.6 with XCode installed. I get the following error:
ld: warning: option -s is obsolete and being ignored
ld: library not found for -lcrt0.o

I was wondering which library do I need to install?

**Full screen dump is here:**
Aras-MacBook-Pro:jpsglouzon-supernmotifs-bcd1b00 ara$ make
g++ -Wall -fexceptions -O3 -std=c++11 -m64 -I. -c main.cpp -o main.o
g++ -Wall -fexceptions -O3 -std=c++11 -m64 -I. -c RepMotif.cpp -o RepMotif.o
g++ -Wall -fexceptions -O3 -std=c++11 -m64 -I. -c RepSupermotif.cpp -o RepSupermotif.o
g++ -Wall -fexceptions -O3 -std=c++11 -m64 -I. -c RepWeightedMotif.cpp -o RepWeightedMotif.o
g++ -L. -o supernmotifs main.o RepMotif.o RepSupermotif.o RepWeightedMotif.o -s -m64 -static -static-libgcc -static-libstdc++ 
ld: warning: option -s is obsolete and being ignored
ld: library not found for -lcrt0.o
collect2: error: ld returned 1 exit status
make: *** [supernmotifs] Error 1

**gcc version info:**
Aras-MacBook-Pro:jpsglouzon-supernmotifs-bcd1b00 ara$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin14.0.0/4.9.2/lto-wrapper
Target: x86_64-apple-darwin14.0.0
Configured with: ../gcc-4.9-20141029/configure --enable-languages=c++,fortran
Thread model: posix
gcc version 4.9.2 20141029 (prerelease) (GCC)

**Comment by jpsglouzon** [comment]
Hi,


I think the problem is related to the -static flag in the makefile.

You could try to remove it and test if it works.


________________________________
De : Winter <notifications@github.com>
Envoyé : 7 mars 2017 09:42
À : jpsglouzon/supernmotifs
Cc : Subscribed
Objet : [jpsglouzon/supernmotifs] Compiling on OSX 10.11.6 with XCode (#1)


Hello,

I am trying to run the make command on supernmotifs from source. I am running OSX 10.11.6 with XCode installed. I get the following error:
ld: warning: option -s is obsolete and being ignored
ld: library not found for -lcrt0.o

I was wondering which library do I need to install?

Full screen dump is here:
Aras-MacBook-Pro:jpsglouzon-supernmotifs-bcd1b00 ara$ make
g++ -Wall -fexceptions -O3 -std=c++11 -m64 -I. -c main.cpp -o main.o
g++ -Wall -fexceptions -O3 -std=c++11 -m64 -I. -c RepMotif.cpp -o RepMotif.o
g++ -Wall -fexceptions -O3 -std=c++11 -m64 -I. -c RepSupermotif.cpp -o RepSupermotif.o
g++ -Wall -fexceptions -O3 -std=c++11 -m64 -I. -c RepWeightedMotif.cpp -o RepWeightedMotif.o
g++ -L. -o supernmotifs main.o RepMotif.o RepSupermotif.o RepWeightedMotif.o -s -m64 -static -static-libgcc -static-libstdc++
ld: warning: option -s is obsolete and being ignored
ld: library not found for -lcrt0.o
collect2: error: ld returned 1 exit status
make: *** [supernmotifs] Error 1

-

**Comment by anmwinter** [comment]
Thank you! Removing the -static flag in the make file fixed the issue. It does throw a bunch of warnings like:
ld: warning: direct access in std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&) to global weak symbol std::ctype<char>::do_widen(char) const means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

But it runs fine.

**Comment by jpsglouzon** [comment]
Glad to hear it works.


________________________________
De : Winter <notifications@github.com>
Envoyé : 7 mars 2017 11:51
À : jpsglouzon/supernmotifs
Cc : Jean-Pierre Sehi Glouzon; Comment
Objet : Re: [jpsglouzon/supernmotifs] Compiling on OSX 10.11.6 with XCode (#1)


Thank you! Removing the -static flag in the make file fixed the issue. It does throw a bunch of warnings like:
ld: warning: direct access in std::basic_ostream<char, std::char_traits >& std::endl<char, std::char_traits >(std::basic_ostream<char, std::char_traits >&) to global weak symbol std::ctype::do_widen(char) const means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

But it runs fine.

-
